website/core/urls.py
from django.views.generic import View, TemplateView
from django.conf.urls import url
from core.views import *


urlpatterns = [
	url(r'^news/(?P<pk>\d+)/$', CurrentNew.as_view(), name='current_new'),
	url(r'^news/$', NewsPage.as_view(), name='news'),
	url(r'^change_mode/$', ChangemodeView.as_view(), name='changemode'),
	url(r'^about/ofitsialnye-rekvizity/$', RekvizityPage.as_view(),
		name='of_rekvisity'),
	# собственные шаблоны для страниц -----------
	url(r"^about/kvalifikatsionnye-kategorii/",
		CustomTemplatePage.run_view(template_name="about/category.html",
			id_page=3),
		name="kategorii"),
	# -------------------------------
	# для всех шаблонов, которые берутся из БД, если код страницы не найден,
	#то будет вставлен шаблон "page_in_development"
	url(r'^$', IndexPage.as_view(), name='main_page'),
	url(r'^(?P<path>.*)$', CommonTemplatePage.as_view(), name='common_template'),
]

"""
	обычные страницы, здесь их можно добавлять
	url_page и id_page берутся из таблицы основное меню из полей "ссылка" и id
	template_name - путь к html файлу, пример:
	url(r"^<url_page>/",
	CommonTemplatePage.run_view(template_name="about/kategorii.html",
								id_page=<id_page>), name="<name>")
"""

website/website/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^markitup/', include('markitup.urls')),
    #url(r'^ckeditor/',  include ( 'ckeditor_uploader')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# обязательно добавляем в конце из-за правила common_template
urlpatterns.append(url(r'^', include('core.urls', namespace="core")),)

"""
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

website/core/models.py
from django.db import models
from ckeditor.fields import RichTextField
#from markitup.fields import MarkupField

# Create your models here.


class FilesStore(models.Model):

    class Meta:
        verbose_name = "Файлопомойка"
        verbose_name_plural = "Загруженные файлы"

    about = models.CharField(max_length=255, default="", null=True, blank=True,
        verbose_name="Краткое описание (необязательно)")
    caption = models.CharField(max_length=255, default="",
        null=True, blank=True,
        verbose_name="Название файла (необязательно)")
    file = models.FileField(verbose_name='Файл', upload_to='files/%Y/%m/%d')

    def __str__(self):
        return f"file {self.caption} - {self.about}"


class OfitsialnyeRekvizity(models.Model):

    class Meta:
        verbose_name = "Реквизит"
        verbose_name_plural = "Официальные реквизиты"
        ordering = ("id",)

    #label = models.CharField(max_length=255)
    #text = models.TextField(default="")
    label = RichTextField()
    text = RichTextField()


class Slider(models.Model):

    class Meta:
        verbose_name = "Слайд"
        verbose_name_plural = "Слайдер"

    title = models.CharField(max_length=255, verbose_name="Заголовок")
    text = models.CharField(max_length=255, verbose_name="Текст")
    url = models.CharField(max_length=255, verbose_name="ссылка", blank=True,
        null=True,
        help_text="Если пустой, то кнопка перехода на слайде не отображается")
    image = models.ImageField(upload_to='slider/%Y/%m/%d',
        verbose_name='Картинка',
        help_text="Рекомендуется загружать картинки с прозрачным фоном в .png")


class TopicButtons(models.Model):

    class Meta:
        verbose_name = "Пункт меню"
        verbose_name_plural = "Основное меню"
        ordering = ['order', 'id']

    caption = models.CharField(max_length=255, verbose_name="Название")
    url = models.CharField(max_length=255, verbose_name="ссылка")
    parent = models.ForeignKey('self', blank=True, null=True,
        verbose_name='Вложено в ', on_delete=models.CASCADE)
    second_level_link = models.BooleanField(default = False,
        verbose_name='Вложенный пункт меню',
        help_text="True - для подпунктов меню")
    order = models.IntegerField(verbose_name='порядок', default=100)

    def __str__(self):
        return self.caption


class DocumentsStore(models.Model):

    class Meta:
        verbose_name = "Документ"
        verbose_name_plural = "Документы для страниц сайтов"
        ordering = ("id",)

    document = models.OneToOneField(FilesStore, on_delete=models.CASCADE,
        help_text="Указатель на загруженный файл")
    label = models.CharField(max_length=255, default="link to document",
        help_text="Текст ссылки на документ")
    page = models.ForeignKey(TopicButtons, on_delete=models.CASCADE,
        help_text="Указатель на страницу, которой принадлежит документ")
    caption = models.CharField(max_length=255, null=True, blank=True,
        help_text="Заголовок (необязателен) для сслыки")


class ArticlesNews(models.Model):

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"
        ordering = ["-created"]

    title = models.CharField(max_length=255, verbose_name="Заголовок")
    preview = models.TextField(default="", verbose_name="Короткий текст")
    image = models.ImageField(upload_to='files/%Y/%m/%d', null=True, blank=True,
        help_text="Лучше использовать картинки с одинаковыми высотой и шириной")
    created = models.DateTimeField(auto_now_add=True)
    #text = models.TextField(default="")
    text = RichTextField()

website/core/views.py
import os
from django.conf import settings
from django.utils.decorators import classonlymethod
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.views.generic import View, TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from core.models import *

# Create your views here.


class IndexPage(ListView):
    template_name = "index.html"
    queryset = ArticlesNews.objects.all()[:10]

    def get(self, request, *args, **kwargs):
        return super(IndexPage, self).get(request)

    def get_context_data(self, **kwargs):
        context = super(IndexPage, self).get_context_data(**kwargs)
        context["slider"] = Slider.objects.all()
        return context


class NewsPage(ListView):
    template_name = "news.html"
    queryset = ArticlesNews.objects.all()


class CurrentNew(DetailView):
    template_name = "current_new.html"
    model = ArticlesNews


class ChangemodeView(View):

    def get(self, request, *args, **kwargs):
        try:
            old_url = request.META["HTTP_REFERER"]
        except:
            old_url = '/'
        # сменяем значение куки
        low_vision_mode = not request.session.get("low_vision_mode", False)
        request.session["low_vision_mode"] = low_vision_mode
        request.session.set_expiry(0)
        return HttpResponseRedirect(old_url)


class RekvizityPage(ListView):
    template_name = "about/rekvizity.html"
    model = OfitsialnyeRekvizity

    def get_context_data(self, **kwargs):
        context = super(RekvizityPage, self).get_context_data()
        context["documents"] = DocumentsStore.objects.filter(page=2)
        return context


class CustomTemplatePage(TemplateView):
    """Универсальное представление для собственных шаблонов"""
    page_id = None

    def get_context_data(self, **kwargs):
        context = super(CustomTemplatePage, self).get_context_data()
        context["documents"] = DocumentsStore.objects.filter(page=self.page_id)
        return context

    @classonlymethod
    def run_view(cls, template_name, id_page, **initkwargs):
        print("runView")
        cls.page_id = id_page
        cls.template_name = template_name
        return cls.as_view()


class CommonTemplatePage(TemplateView):
    """Универсальное представление для страниц, сделанных через WYSIWYG"""
    template_name = "common_templates/page_in_development.html"

    def get(self, request, *args, **kwargs):
        url = request.META['PATH_INFO']
        obj = TopicButtons.objects.filter(url=url).first()
        if obj is None:
            raise Http404("Такая страница не найдена")
        kwargs.update(page_title=obj.caption)
        return super(CommonTemplatePage, self).get(request, *args, **kwargs)

website/templates/about/category.html
{% extends "base.html" %}

{% block page_title %}
<div id="page-title">
	<div id="page-title-inner">
		<div class="container">
			<h3 style='text-transform: uppercase; color: white;'>Квалификационные категории</h3>
		</div>
	</div>
</div>
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
        	<p>Со списком квалификационных категорий врачей, среднего и младшего медицинского персонала КГБУЗ"Красноярская городская поликлиника № 14" Вы можете ознакомиться, скачав прикрепленный файл:</p>
        	{% for doc in documents %}
        		{% if doc.caption %}
        		<div class="title"><h3>{{doc.caption}}</h3></div>
        		{% endif %}
        		<p class="subtitle-text">
        			<a target="blank" href="{{doc.document.file.url}}">{{doc.label}}</a>
        		</p>
        	{% endfor %}
        </div>
    </div>
{% endblock %}

website/templates/about/rekvizity.html
{% extends "base.html" %}

{% block page_title %}
<div id="page-title">
	<div id="page-title-inner">
		<div class="container">
			<h3 style='text-transform: uppercase; color: white;'>Официальные реквизиты</h3>
		</div>
	</div>
</div>
{% endblock %}


{% block content %}
    <div class="row">
        <div class="col-md-12">
        	<div class="title"><h3>Общая информация об учреждении</h3></div>
        	<table class="table table-striped">
        		<tbody>
        			{% for item in object_list %}
        			<tr>
        				<td>
        					{{item.label | safe}}
        				</td>
        				<td>
        					{{item.text | safe}}
        				</td>
        			</tr>
        			{% endfor %}
        		</tbody>
        	</table>
        	{% for doc in documents %}
        		{% if doc.caption %}
        		<div class="title"><h3>{{doc.caption}}</h3></div>
        		{% endif %}
        		<p class="subtitle-text">
        			<a target="blank" href="{{doc.document.file.url}}">{{doc.label}}</a>
        		</p>
        	{% endfor %}
        	<!--
        	<div class="title"><h3>Лицензии</h3></div>
        	<p class="subtitle-text"> - Лицензия на осуществление мед. деятельности от 21.06.2018</p>
        	<div class="title"><h3>Свидетельства</h3></div>
        	<p class="subtitle-text"> - Свидетельство о внесении записей в ЕГРЮЛ от 08.08.2002 </p>
        	<div class="title"><h3>Устав</h3></div>
        	<p class="subtitle-text"> - Устав КГП №14</p>
        	<div class="title"><h3>ИНН</h3></div>
        	<p class="subtitle-text">2465004033</p>
        -->
        </div>
    </div>
{% endblock %}

website/templates/block_news.html
{% load staticfiles %}

{% for item in object_list %}
<div class="row">
    <div class="icons-box-vert-container">
        {% if request.session.low_vision_mode %}
        <div class="span12">
        {% else %}
        <div>
        {% endif %}
            <div class="icons-box-vert">
                <a href="{% url 'core:current_new' pk=item.id %}">
                <img class="circle-color small img-article" src="{{item.image.url}}">
                <div class="icons-box-vert-info">
                    <h3>{{item.title}}</h3>
                    <p class="preview-text">{{item.preview}}</p>
                </div>
                <div class="clear"></div>
                </a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

website/templates/common_templates/page_in_development.html
{% extends "base.html" %}

{% block page_title %}
<div id="page-title">
    <div id="page-title-inner">
        <div class="container">
            <h3 style='text-transform: uppercase; color: white;'>
                {{page_title}}
            </h3>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="row">
        <center>
        <img src="/media/stranitsa-v-razrabotke.jpg">
        </center>
    </div>
{% endblock %}

website/templates/current_new.html
{% extends "base.html" %}
{% load staticfiles %}

{% block page_title %}
<div id="page-title">
	<div id="page-title-inner">
		<div class="container">
			<h3 style='text-transform: uppercase; color: white;'>&nbsp;</h3>
		</div>
	</div>
</div>
{% endblock %}

{% block content %}

<div class="row">
		
	<div class="span12">				
		<!-- start: About Us -->
		<div id="about">
                <img class="news_img" src="{{object.image.url}}">
			<div class="title news_title"><h3>{{object.title}}</h3></div>
			<p class="news_body">{{object.text | safe}}</p>
		</div>	
		<!-- end: About Us -->
	</div>	
				
</div>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block slider%}
    <div class="slider-wrapper">
        <div id="da-slider" class="da-slider">
            {% for slide in slider%}
                <div class="da-slide">
                <h2>{{slide.title}}</h2>
                <p>{{slide.text}}</p>
                {% if slide.url %}
                    <a href="{{slide.url}}" class="da-link">Перейти</a>
                {% endif %}
                <div class="da-img"><img src="{{slide.image.url}}" alt="image01" /></div>
            </div>
            {% endfor %}
            <nav class="da-arrows">
                <span class="da-arrows-prev"></span>
                <span class="da-arrows-next"></span>
            </nav>
        </div>  
    </div>
{% endblock %}

{% block content %}
    <div class="row">
        {% include 'block_news.html' %}
    </div>
{% endblock %}

website/templates/news.html
{% extends "base.html" %}
{% load staticfiles %}

{% block page_title %}
<div id="page-title">
	<div id="page-title-inner">
		<div class="container">
			<h3 style='text-transform: uppercase; color: white;'>Новости</h3>
		</div>
	</div>
</div>
{% endblock %}

{% block content %}
<div class="row">
    {% include 'block_news.html' %}
</div>
{% endblock %}